# Gopkg.toml for this project.
#

required = [
    "github.com/stretchr/testify",
]

[[constraint]]
   name = "github.com/stretchr/testify"
   version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
